name: Release Creation

on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
   
    - name: Version  
      id: create_version  
      uses: juliansangillo/tag-version@v1  
      with:  
          production-branch: main
          test-branch: test
          dev-branch: develop

    - name: Echo tag output
      run: echo ${{ steps.create_version.outputs.revision }}

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{steps.create_version.outputs.revision}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/v${{steps.create_version.outputs.revision}}/fvtt-tinymce-checklist.zip

    # Create a zip file with all files required by the module to add to the release
    - run: zip -r ./fvtt-tinymce-checklist.zip module.json scripts/ styles/ templates/ lang/

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json, ./fvtt-tinymce-checklist.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}